### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by xMacoy01** [vanhbakaa/Hamster-kombat#1]
![image](https://github.com/user-attachments/assets/f8923b14-989f-4e74-bdda-9021bb8a90e4)

**Comment by udaydeep1992** [comment]
from bot.core.registrator import register_sessions
ModuleNotFoundError: No module named 'bot.core.registrator'

**Comment by Lastnet0709** [comment]
it's work for me
copy file registrator.py from another bot paste in bot/core
![image](https://github.com/user-attachments/assets/5286c320-4a64-4325-bf43-1ccd973c6914)
