### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hasan1818666891** [vanhbakaa/Hamster-kombat#3]
POST Request Error: https://api.hamsterkombatgame.io/auth/auth-by-telegram-webapp Response code: 50
0
2024-10-19 14:32:00 | ERROR    | 179 - +16304894675 | 🔑 Failed to login to HamsterKombat bot!

**Comment by thapld** [comment]
same, please fix it

**Comment by bootfast** [comment]
ID Banned 🚫🚫🚫

**Comment by vanhbakaa** [comment]
> ID Banned 🚫🚫🚫

??

**Comment by vanhbakaa** [comment]
> POST Request Error: https://api.hamsterkombatgame.io/auth/auth-by-telegram-webapp Response code: 50 0 2024-10-19 14:32:00 | ERROR | 179 - +16304894675 | 🔑 Failed to login to HamsterKombat bot!

IT'S SERVER ERROR NOT MY BOT BRUH
